import React from 'react';

import Hero from '../components/Hero';
import Content from '../components/Content';

function AboutPage(props) {
    return(
        <div>
            <Hero title={props.title}></Hero>

            <Content>
                <p>Hello, my name is Ethan (Holt) Picklesimer. I am a software engineering major at BYU-Idaho, graduating in April 2021. I have experience in C#, .NET, SQL, HTML, CSS, JavaScript, jQuery, PHP, Node.js, C++, C, Java, and Python. I have done work in R and Erlang, and I developed this website using React.</p>
                <p>I have worked as an application development intern on the Enrollment Application Development Team at CareSource, a healthcare company located in Dayton, OH, since May of 2019. While finishing my Bachelor's degree, they have allowed me to work part-time remotely while in school and full-time when I am off-track. During my time at CareSource, I have had the opportunity to work in a Scrum team and learn how to do many of the process of Agile, including writing user stories and design documents, participating in sprint plannings, retrospectives, and reviews. I am the main contributor of the Enrollment Engine Regression Testing Tool, which is used to verify existing code does not break when changes are made to the Enrollment Engine code and has been used as a model for other regression tools in the company. While working on the regression tool, I used .NET Framework, Razor webpages, SQL, Javascript and jQuery to create mock data to test the Enrollment Engine. Besides the regression testing tool, I have created a dynamic mapping table to store mappings, as well as a UI for a configuration management system to allow for easy access creating and modifying compliance items.</p>
                <p>In my school projects, I was the lead program architect for the development of a scheduling and budgeting Android app. I am currently working on a new and completely redone version of this app since it has been taken off GitHub by one of my teammates and I wanted to make a polished version to put on the app store. I also had the chance to work in another group with two other teammates to develop a <a href="https://github.com/HoltPicklesimer/Gender-Classification" target="_blank">neural network gender classifier</a>. I led the research for this project to test different layers in a neural network using the Keras and TensorFlow Python libraries. I also developed an image sorting program to prepare the data before classification since it was sorted by name rather than by gender. The program uses the labels file provided by the dataset to sort each image into either a male or female folder. The dataset used was the <a href="http://vis-www.cs.umass.edu/lfw/" target="_blank">Labeled Faces in the Wild</a> dataset, which contains more than 13,000 images. I collaborated with over twenty other teammates to write a <a href="https://github.com/HoltPicklesimer/Grad-Planner-Registration-Integration-Software-Requirements-Specification" target="_blank">software requirements specification</a> and <a href="https://github.com/HoltPicklesimer/Grad-Planner-Registration-Integration-Software-Design-Description" target="_blank">software design description</a> for an integrated graduation planner and class registration system. I also collaborated in another twenty student team to write a <a href="https://github.com/HoltPicklesimer/Mobile-Dating-App-Specification" target="_blank">software design description</a> for a mobile dating app. I have also worked on a few different <a href="https://mighty-gorge-68223.herokuapp.com/Home/assigns.php" target="_blank">web apps</a> using PHP and Node.js</p>
                <p>I am currently a member of the ACM Society and CIT Society at BYU-I. In the ACM Society, we are developing a Unity game in which you control a cannon on an orbiting moon called Artemis which you can check out <a href="https://github.com/byuiacm/Artemis" target="_blank">here</a>. In the CIT society, I am on a team that is working on developing a quiz engine that will allow users to create and take quizzes similar to Canvas or other quiz engines. The quiz engine is being developed with Vue.js and you can check it out <a href="https://github.com/BYUI-CIT-Internship/QuizEngine" target="_blank">here</a>.</p>
                <p>Please check out my <a href="https://github.com/HoltPicklesimer" target="_blank">GitHub</a> page and <a href="https://www.linkedin.com/in/holt-picklesimer" target="_blank">LinkedIn</a>, or contact me using the contact page on this site, at holtpicklesimer@gmail.com, or 234-281-6994.</p>
            </Content>
        </div>
    );
}

export default AboutPage;